name : ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: go test -cover ./...
          
      - name: Success
        run: (exit 0)
  styles:
    name: Styles
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Check Formatting
        run: go test -z $(go fmt ./...)
      
      - name: Success
        run: (exit 0)