name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: go test -cover ./...
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Check Security
        run: gosec ./..

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Formatting
        run: go test -z $(go fmt ./...)
      - name: Install Linter
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Add GOPATH/bin to PATH  # Correct way to set PATH in GitHub Actions
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Check Linting
        run: staticcheck ./...