name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: go test -cover ./...

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Check Formatting
        run: test -z $(go fmt ./...)
       - name: Install Linter
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Add GOPATH/bin to PATH  # Correct way to set PATH in GitHub Actions
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Check Linting
        run: test -z $(staticcheck ./...)